config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'signup'},
    :controllers => { :passwords => "passwords" }
  get 'main/index'

  devise_scope :user do
    match '/sessions/user', to: 'devise/sessions#create', via: :post
  end

  resources :auctions do
    collection do
      get 'my_index'
    end
    resources :bids
  end

  root 'main#index'

  resources :sessions

end

app/models/auction.rb
class Auction < ActiveRecord::Base

  has_many :bids, :dependent => :delete_all
  belongs_to :user

  validates_presence_of :start, :end

  validates_datetime :end, :after => :start

  validates :title, presence: true,
            length: { minimum: 10 }
  validates :text, presence: true
  validates :start, presence: true
  validates :end, presence: true
  validates :kwh, presence: true
  validates :mileage, presence: true
  validates :color, presence: true
  validates :brand, presence: true
  validates :minimum_price, presence: true

  mount_uploader :avatar, AvatarUploader


  def remove_avatar=(val)
    avatar_will_change! if val
    super
  end

  def ended?
    DateTime.now > self.end
  end

  def self.user
    User.find(@user_id)
  end

end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
  before_action :require_permission, only: [:edit, :update, :destroy ]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @search = Auction.search(params[:q])
    if params[:q] == nil then
      @auctions = Auction.all
    else
      @auctions = @search.result
    end

    @collapse_form = params[:show_adv] ? 'collapse in' : 'collapse'

  end

  def show
    @auction = Auction.find(params[:id])
    @highest_bid = @auction.bids.select(&:persisted?).each.max_by(&:amount)
  end

  def new
    @auction = Auction.new
  end

  def edit
  end

  def create
    @auction = current_user.auctions.new(auction_params)

    if @auction.save
      flash[:notice] = "Auction successfully created!"
      redirect_to @auction
    else
      flash[:alert] = "Cannot create auction! Please try again!"
      render 'new'
    end
  end

  def update
    @auction = Auction.find(params[:id])

    if @auction.update(auction_params :update)
      redirect_to @auction
    else
      render 'edit'
    end
  end

  def destroy
    @auction.destroy
    flash[:notice] = "Auction successfully deleted!"
    redirect_to auctions_path
  end

  def my_index
    @auctions = current_user.auctions
  end

  def require_permission
    @auction = Auction.find(params[:id])
    if current_user != @auction.user or @auction.ended?
      flash[:alert] = "Cannot edit this auction!"
      redirect_to auctions_path
    end
  end

  private

    def auction_params(action = :new)
      case action
        when :new
          params.require(:auction).permit(:title, :text, :end, :kwh, :mileage, :color, :brand,
                                          :avatar, :minimum_price, :remove_avatar, :_destroy)
                .merge(start: DateTime.now)
        when :update
          params.require(:auction).permit(:title, :text, :kwh, :mileage, :color, :brand, :avatar,
                                          :minimum_price, :remove_avatar, :_destroy)
      end
    end

end

app/helpers/auctions_helper.rb
module AuctionsHelper
end

app/views/auctions/_bikelist.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        E-Bikes
        <div class="pull-right"><%= link_to 'New auction', new_auction_path %></div>
      </div>
      <!-- /.panel-heading -->
      <div class="panel-body">
        <div class="table-responsive">
          <table class="table">
            <thead>
            <tr>
              <th>Title</th>
              <th>Text</th>
            </tr>
            </thead>
            <tbody>
            <% @auctions.each do |auction| %>
                <tr>
                  <td><%= auction.title %></td>
                  <td><%= auction.text %></td>
                  <td><%= link_to 'Show', auction_path(auction) %></td>
                  <% if user_signed_in? and current_user.id == auction.user_id %>
                      <td><%= link_to 'Edit', edit_auction_path(auction) %></td>
                      <td><%= link_to 'Destroy', auction_path(auction),
                                      method: :delete,
                                      data: { confirm: 'Are you sure?' } %> </td>
                  <% end %>
                </tr>
            <% end %>
            </tbody>
          </table>
        </div>
        <!-- /.table-responsive -->
      </div>
      <!-- /.panel-body -->
    </div>
    <!-- /.panel -->
  </div>
  <!-- /.col-lg-6 -->
</div>
<!-- /.row -->

app/views/auctions/_form.html.erb
<div class="row">
<div class="col-xs-6 col-md-4">
<%= form_for @auction, :html => { :multipart => true, :class => "form-signin"}, locals: [editable, ended] do |f| %>
    <% if @auction.errors.any? %>
        <div id="error_explanation">
          <h3>
            <%= pluralize(@auction.errors.count, 'error') %> prohibited
            this article from being saved:
          </h3>
          <ul>
            <% @auction.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <% if ended %>
      <%= f.label 'The auction has ended!' %>
    <% end %>

    <div class="form-group">
      <%= f.label :title %><br>
      <%= f.text_field :title, class: "form-control", :readonly => ended %>
    </div>

    <div class="form-group">
      <%= f.label :text %><br>
      <%= f.text_area :text, class: "form-control", :readonly => ended %>
    </div>

    <div class="form-group">
      <%= f.label :end %><br>
      <% if editable && !ended %>
          <%= f.datetime_select(:end, {class:"form-control"}) %>
      <% else %>
          <%= f.text_field :end, :value => @auction.end, :readonly => true %>
      <% end %>
    </div>

    <div class="form-group">
      <%= f.label :kwh %><br>
      <%= f.text_field :kwh, class: "form-control", :readonly => ended %>
    </div>

    <div class="form-group">
      <%= f.label :mileage %><br>
      <%= f.text_field :mileage ,class: "form-control", :readonly => ended %>
    </div>

    <div class="form-group">
      <%= f.label :color %><br>
      <%= f.text_field :color,class: "form-control", :readonly => ended %>
    </div>

    <div class="form-group">
      <%= f.label :brand %><br>
      <%= f.text_field :brand, class: "form-control", :readonly => ended %>
    </div>

    <div class="form-group">
      <%= f.label :minimum_price %><br>
      <%= f.text_field :minimum_price, class: "form-control", :readonly => !editable %>
    </div>



    <div class="form-group">
      <%= f.label 'Image' %>
      <%= f.hidden_field :avatar_cache %>
      <%= f.file_field :avatar, :readonly => ended %>
      <% @has_avatar = @auction.avatar? %>
      <% if @has_avatar %>
          <%= image_tag @auction.avatar.url.to_s %>
          <p>
            <label>
              <%= f.check_box :remove_avatar %>
              Remove picture
            </label>
          </p>
      <% else %>
          <b>No Image available!</b>
      <% end %>

    </div>

    <div class="form-group">
      <% if editable && !ended %>
          <%= f.submit "New" , class:"btn btn-lg btn-primary pull-left" %>
      <% elsif !editable && !ended %>
          <%= f.submit "Save Changes" , class:"btn btn-lg btn-primary pull-left" %>
      <% end %>
    </div>
<% end %>
</div>
</div>

app/views/auctions/_search_form.erb
<div class="row">
  <div class="col-sm-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <a role="button" data-target="#adv_auction_search" data-toggle="collapse" class="btn btn-primary">Use advanced
          search</a>
      </div>
      <div class="panel-body">
        <%= search_form_for @search, namespace: "adv",
                            html: {id: 'adv_auction_search',
                                   class: 'form-horizontal '+@collapse_form} do |f| %>

            <%= hidden_field_tag 'show_adv', 1 %>
            <div class="form-group">
              <%= f.label :title_cont, class: 'control-label' %>
              <%= f.search_field :title_cont %>
            </div>
            <div class="form-group">
              <%= f.label :text_cont, class: 'control-label' %>
              <%= f.search_field :text_cont %>
            </div>
            <div class="form-group">
              <%= f.label :color_cont, class: 'control-label' %>
              <%= f.search_field :color_cont %>
            </div>
            <div class="form-group">
              <%= f.label :brand_cont, class: 'control-label' %>
              <%= f.search_field :brand_cont %>
            </div>
            <div class="form-group between">
              <%= f.label :mileage_gt, 'Mileage (km) between', class: 'control-label' %>

              <%= f.text_field :mileage_gt %>
              <%= f.label :mileage_lt, 'and', class: 'control-label' %>
              <%= f.text_field :mileage_lt %>
            </div>
            <div class="form-group between">
              <%= f.label :kwh_gt, 'Capacity (kWh) between', class: 'control-label' %>

              <%= f.text_field :kwh_gt %>
              <%= f.label :kwh_lt, 'and', class: 'control-label' %>
              <%= f.text_field :kwh_lt %>
            </div>
            <div class="form-group">
              <%= f.label :user_username_eq, 'Seller username is', class: 'control-label' %>
              <%= f.search_field :user_username_eq %>
            </div>
            <div class="form-group">
              <%= f.submit class: 'col-sm-offset-3' %>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/auctions/edit.html.erb
<h2>Editing Auction</h2>
<%= link_to 'Back', auctions_path %>
<%= render partial: 'form', :locals => { :editable => false, :ended => @auction.ended? } %>

app/views/auctions/index.html.erb
<h2>Auctions</h2>

<%= render'search_form' %>

<%= render 'bikelist' %>

app/views/auctions/my_index.html.erb
<h1>My Auctions</h1>

<%= render 'bikelist' %>

app/views/auctions/new.html.erb
<h2>New Auction</h2>

<%= link_to 'Back', auctions_path %>

<%= render partial: 'form', :locals => { :editable => true, :ended => false} %>

app/views/auctions/show.html.erb
<h1>Auction Overview</h1>
<div class="row">
  <div class="col-xs-12 col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <b><%= @auction.title %></b>
      </div>
      <!-- /.panel-heading -->
      <div class="panel-body">
        <div class="col-xs-12 col-md-6">
        <div class="row">
          <b>Title: </b> <%= @auction.title %>
        </div>
        <div class="row">
          <b>Text: </b> <%= @auction.text %>
        </div>
        <div class="row">
          <b>Start: </b> <%= @auction.start.strftime("%d %B %Y, %H:%M%p") %>
        </div>
        <div class="row">
          <b>End: </b> <%= @auction.end.strftime("%d %B %Y, %H:%M%p") %>
        </div>
        <div class="row">
          <b>KWh: </b> <%= @auction.kwh %>
        </div>
        <div class="row">
          <b>Mileage: </b> <%= @auction.mileage %>
        </div>
        <div class="row">
          <b>Color: </b> <%= @auction.color %>
        </div>
        <div class="row">
          <b>Brand: </b> <%= @auction.brand %>
        </div>
        <div class="row">
          <b>Seller: </b> <%= @auction.user.username %>
        </div>
        <div class="row">
          <b>Share:</b> <br><a href="https://twitter.com/share" class="twitter-share-button">Tweet</a>
          <!--<div class="fb-share-button" data-href="https://developers.facebook.com/docs/plugins/" data-layout="button"></div>-->
        </div>
      </div>
      <div class="col-xs-12 col-md-6">
        <div class="row">
          <h4><b>Image</b></h4>
          <% @has_avatar = @auction.avatar? %>
          <% if @has_avatar %>
          <%= image_tag @auction.avatar.url.to_s %>
          <% else %>
          <b>No Image available!</b>
          <% end %>
        </div>

      </div>
      </div>
      <!-- /.panel-body -->
    </div>
    <!-- /.panel -->
  </div>
  <!-- /.col-lg-6 -->
</div>
<!-- /.row -->
<div class="row">
  <div class="col-xs-12 col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <b>Bids</b>
      </div>
      <!-- /.panel-heading -->
      <div class="panel-body">
        <div class="col-xs-12 col-md-6">
          <div class="row">
            <b>Current bid: </b>
            <% if @highest_bid %>
                <%= @highest_bid.amount %>
            <% else %>
                <%= @auction.minimum_price %>
            <% end %>
          </div>
        </div>
        <div class="col-xs-12 col-md-6">
          <div class="row">
            <% if @highest_bid %>
                <b>Highest bidder: </b>
                <%= @highest_bid.user.username %>
            <% else %>
                <b>No bid yet</b>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<% if !@auction.ended? %>
    <% if current_user == @auction.user %>
        <%= link_to 'Edit', edit_auction_path(@auction) %> |
    <% end %>
    <%= link_to 'Back', auctions_path %>
<div class="row">
  <% if user_signed_in? %>
    <% unless current_user.username == @auction.user.username %>
      <h2>Place a bid</h2>
      <%= render 'bids/form'  %>
    <% end %>
  <% else %>
    <h2>Place a bid</h2>
    <%= link_to 'Log In to place a bid', new_user_session_path %>
  <% end %>
<% else %>
    <%= 'The auction has ended! You cannot place bids anymore!' %>
    <%= link_to 'Back', auctions_path %>
<% end %>
</div>