config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'signup'},
    :controllers => { :passwords => "passwords" }
  get 'main/index'

  devise_scope :user do
    match '/sessions/user', to: 'devise/sessions#create', via: :post
  end

  resources :auctions do
    collection do
      get 'my_index'
    end
    resources :bids
  end

  root 'main#index'

  resources :sessions

end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<br />
<div class="container">
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'E-Bikes', root_path, class: 'navbar-brand', style: "font-weight: bold" %>
    </div>
    <div class="collapse navbar-collapse">
      <div class="col-lg-4 nav" style="margin-top:8px">
        <%= form_tag auctions_path, method: "get" do %>
            <div class="input-group">
              <%= search_field_tag 'q[title_or_text_or_color_or_brand_cont]', nil, class: "form-control", placeholder: "Search auctions..." %>
              <span class="input-group-btn">
                <%= submit_tag 'Search', class: "btn btn-default" %>
              </span>
            </div><!-- /input-group -->
        <% end %>
      </div><!-- /.col-lg-6 -->
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>
</div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

<% if user_signed_in? %>
    <%= link_to 'My Auctions', my_index_auctions_path, class: 'navbar-brand' %>
<% end %>
<%= link_to 'All Auctions', auctions_path, class: 'navbar-brand' %>

<% if user_signed_in? %>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="glyphicon glyphicon-user"></i> <%= current_user.username %><b class="caret"></b></a>
  <ul class="dropdown-menu">
    <li>
      <%= link_to edit_user_registration_path do %>
          <span class="glyphicon glyphicon-user"></span>
          Profile
      <% end %>
    </li>
    <li>
      <%= link_to destroy_user_session_path, :method => :delete do %>
          <span class="glyphicon glyphicon-log-out"></span>
          Log Out
      <% end %>
    </li>
  </ul>
</li>
<% else %>
<%= link_to 'Sign Up', new_user_registration_path, class: 'navbar-brand' %>
<%= link_to new_user_session_path, class: 'navbar-brand'  do%>
        <span class="glyphicon glyphicon-log-in"></span>
        Log In
<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Bike Trader" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Bike Trader" %>">
    <%= stylesheet_link_tag 'signin' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <div class="container">
        <main role="main">
           <%= render 'layouts/messages' %>
           <%= yield %>
        </main>
    </div>
  </body>
</html>